name: Python application

on: 
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: rlespinasse/github-slug-action@1.0.0
    - name: Merge source branch with testing
      shell: bash
      run: |
        git checkout testing
        git config user.name "CI"
        git config user.email "tjreverb@gmail.com"
        git pull origin ${{ env.GITHUB_HEAD_REF_SLUG }}
    
    - name: Run test cases
      shell: bash
      run: |
        python submodules/tests.py
        
    
